# Generated by Django 4.2.20 on 2025-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('video_url', models.URLField()),
                ('image', models.URLField()),
                ('recipe_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
