# Generated by Django 4.2.20 on 2025-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
